### ISSUE TITLE
tag new version?

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaML/MLDataUtils.jl#40] opened 2018-05-18 06:26 UTC
adding MLDataUtils just caused this
```julia
julia> Pkg.add("MLDataUtils")
INFO: Cloning cache of DataArrays from https://github.com/JuliaStats/DataArrays.jl.git
INFO: Cloning cache of MLDataPattern from https://github.com/JuliaML/MLDataPattern.jl.git
INFO: Cloning cache of MLDataUtils from https://github.com/JuliaML/MLDataUtils.jl.git
INFO: Cloning cache of MLLabelUtils from https://github.com/JuliaML/MLLabelUtils.jl.git
INFO: Cloning cache of NullableArrays from https://github.com/JuliaStats/NullableArrays.jl.git
INFO: Downgrading CSV: v0.2.4 => v0.1.5
INFO: Downgrading CategoricalArrays: v0.3.9 => v0.1.6
INFO: Installing DataArrays v0.6.2
INFO: Downgrading DataFrames: v0.11.6 => v0.10.1
INFO: Downgrading DataStreams: v0.3.4 => v0.1.3
INFO: Installing MLDataPattern v0.4.0
INFO: Installing MLDataUtils v0.2.0
INFO: Installing MLLabelUtils v0.2.1
INFO: Installing NullableArrays v0.1.2
INFO: Downgrading PooledArrays: v0.2.1 => v0.1.1
INFO: Downgrading TextParse: v0.5.0 => v0.4.1
INFO: Downgrading WeakRefStrings: v0.4.6 => v0.2.0
INFO: Building SpecialFunctions
INFO: Building CodecZlib
INFO: Package database updated
```

**Comment by Evizero** [comment] 2018-05-18 06:36
That is weird. Any idea which package/requirement causes this? I don't see any upper version in the REQUIRE of the relevant JuliaML packages

**Comment by CarloLucibello** [comment] 2018-05-18 07:41
I don't understand the details, but I think it has to do with the deprecation of the nullable ecosystem

**Comment by ppalmes** [comment] 2018-05-22 23:10
Yes, this downgrade is a pain because it causes RCall and maybe other packages to not work. I think it's not a good idea for Pkg.add() to automatically downgrade packages just to satisfy one package because it will affect other packages that depend on those downgraded packages. It should warn or at least provide a yes/no response before downgrade.

**Comment by Evizero** [comment] 2018-05-23 06:13
again, I don't think its MLDataUtils itself that does that

**Comment by Evizero** [comment] 2018-05-23 06:41
actually, I am wrong, sorry. Turns out when the DataFrames code was updated, a max version in REQUIRE was set in the METADATA repo. This is likely the cause and should be fixed on master. I'll tag a new version

**Comment by Evizero** [comment] 2018-05-23 06:43
https://github.com/JuliaLang/METADATA.jl/pull/14801

**Comment by Evizero** [comment] 2018-05-23 13:10
should be fixed now with a `Pkg.update()`

**Closed as completed by Evizero** 2018-05-23 13:10 UTC
